name: parlera
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.0+5

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  shared_preferences: ^2.1.0
  package_info_plus: ^3.0.3
  scoped_model: ^2.0.0-nullsafety.0
  sensors_plus: ^2.0.2
  audioplayers: ^3.0.1
  vibration: ^1.7.4
  wakelock: ^0.6.1
  url_launcher: ^6.1.10
  flutter_device_type: ^0.4.0
  path_provider: ^2.0.12
  share_plus: ^6.3.1
  cross_file: ^0.3.3
  animated_toggle_switch: ^0.6.2
  smooth_page_indicator: ^1.0.1
  palette_generator: ^0.3.3
  sembast: ^3.4.0
  emoji_picker_flutter: ^1.5.2
  flutter_svg: ^1.1.6
  flutter_svg_provider: ^1.0.3
  file_picker: ^5.2.7
  path: ^1.8.2
  xdg_directories: ^1.0.0
  flutter_localized_locales: ^2.0.4
  l10n_esperanto: ^2.0.3

  # TODO CAMERA: Make it work and work well
  # camera: ^0.9.4
  # permission_handler: ^8.3.0
  # carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/data/
    - assets/images/
    - assets/images/tutorial/
    - assets/audio/
    - assets/emoji/

  fonts:
    - family: NotoEmoji
      fonts:
      - asset: assets/fonts/NotoEmoji-Regular.ttf
    - family: MontserratAlternates
      fonts:
        - asset: assets/fonts/MontserratAlternates-Medium.ttf
        - asset: assets/fonts/MontserratAlternates-Bold.ttf
          weight: 700