name: flatpak

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  deploy_flatpak:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3

      - name: Extract version info
        run: |
          echo "VERSION=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_ENV

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: |
          git config --global --add safe.directory /opt/hostedtoolcache/flutter/stable-*
          sudo apt update
          sudo apt install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
          sudo apt install -y libunwind-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev # audioplayers package

      - name: Build for Linux
        run: |
          flutter config --no-analytics
          flutter pub get
          flutter gen-l10n
          flutter build linux --release

      - name: Package Linux build
        run: |
          cd flatpak/scripts
          dart pub get
          dart flatpak_packager.dart --meta ../flatpak_meta.json --github
          cd ../..

      - name: Get latest release
        run: |
          RELEASE_ID=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.id')
          echo "RELEASE_ID=${RELEASE_ID}" >> $GITHUB_ENV

      - name: Upload package
        uses: svenstaro/upload-release-action@v2
        with:
          file: flatpak/scripts/flatpak_generator exports/
          tag: ${{ env.RELEASE_ID }}

      - name: Upload package and its SHA
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          file_glob: true
          file: flatpak/scripts/flatpak_generator exports/parlera-*