name: flatpak

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  deploy_flatpak:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3

      - name: Extract version info
        run: |
          echo "VERSION=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_ENV

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: |
          sudo apt install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
          sudo apt install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev # audioplayers package

      - name: Build for Linux
        run: |
          flutter config --no-analytics
          flutter pub get
          flutter gen-l10n
          flutter build linux --release

      - name: Package Linux build
        run: |
          cd flatpak/scripts
          dart pub get
          dart flatpak_packager.dart --meta ../flatpak_meta.json --github

      - name: Create Github release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          files: |
            flatpak/scripts/flatpak_generator exports/parlera-linux-x86_64.tar.gz
            flatpak/scripts/flatpak_generator exports/parlera-linux-x86_64.sha256